services:
  peertube2nostr:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /app
    volumes:
      - ./data:/data
    environment:
      DB_PATH: /data/peertube2nostr.db
      NSEC_FILE: /data/peertube2nostr.db.nsec
    command: ["run"]
